# Generated by Django 4.2.2 on 2023-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='description',
            field=models.CharField(default='No description available', max_length=1000),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='number_of_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='year',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
