# Generated by Django 4.2.2 on 2023-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0003_gamepublisher_gameboard_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
    ]
