# Generated by Django 4.2.2 on 2023-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0004_alter_gameboard_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameboard',
            name='type',
        ),
        migrations.AddField(
            model_name='gameboard',
            name='category',
            field=models.ManyToManyField(to='gameboard.gameboardcategory'),
        ),
    ]
